import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CiSearch } from "react-icons/ci";
import Link from "next/link";
import logo from '../../public/SHOP.svg'
import { FaShoppingCart } from "react-icons/fa";
import { FaRegUserCircle } from "react-icons/fa";
import { FaInstagramSquare } from "react-icons/fa";
import { FaGithub } from "react-icons/fa";
import { FaFacebookF } from "react-icons/fa";
import { FaTwitter } from "react-icons/fa6";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="">
          <header>
            <div className="bg-black text-white  py-2">
              <h4 className="text-center text-[14px]">Sign up and get 20% off to your first order. <span className="underline cursor-pointer">Sign Up Now</span></h4>
            </div>
            <div className="shadow-lg">
              <div className="flex items-center justify-between  h-[96px] container">
                <div className="container flex items-center gap-5">
                  <div>
                    <img src='/SHOP.svg' alt="" />
                  </div>
                  <div className="flex items-center gap-4">
                    <select className="">
                      <option value="1">Shop</option>
                    </select>
                    <Link className="text-[18px]" href={'/'}>On Sale</Link>
                    <Link className="text-[18px]" href={'/abaut'}>New Arrivals</Link>
                    <Link className="text-[18px]" href={'/cart'}>Brands</Link>
                  </div>
                </div>
                <div className="flex items-center gap-12">
                  <div>
                    <input className="w-[557px] h-[48px] outline-none  bg-[#F0F0F0] rounded-[62px] pl-[52px]" type="search" placeholder="Search for products..." />
                    {/* <span className="text-[20px] font-bold relative top-[-35px] left-[20px]"><CiSearch /></span> */}
                  </div>
                  <span style={{ fontSize: '24px', cursor: 'pointer' }}><FaShoppingCart /></span>
                <Link href="/login" style={{ fontSize: '24px', cursor: 'pointer', textDecoration: 'none', color: 'inherit' }}>
                    <FaRegUserCircle />
                </Link>
                </div>
              </div>
            </div>
          </header>
          <div className="container ">
            {children}
          </div>
          <footer className="bg-[#F0F0F0] h-[400px] pt-[50px]">
            <div className="flex items-center container justify-between mb-8">
              <div>
                <img className="mb-4" src='/SHOP.svg' alt="" />
                <p>We have clothes that suits your style and <br /> which you’re proud to wear. From <br /> women to men.</p>
                <div className="flex items-center gap-4 pt-4">
                  <span className="w-8 h-8 rounded-full bg-white flex items-center justify-center"><FaTwitter /></span>
                  <span className="w-8 h-8 rounded-full bg-white flex items-center justify-center"><FaFacebookF /></span>
                  <span className="w-8 h-8 rounded-full bg-white flex items-center justify-center"> <FaInstagramSquare /></span>
                  <span className="w-8 h-8 rounded-full bg-white flex items-center justify-center"><FaGithub /></span>
                </div>
              </div>
              <div className="flex flex-col gap-3">
                <span className="font-bold mb-1"><Link href={'#'}>Resources</Link></span>
                <Link href={'#'}>About</Link>
                <Link href={'#'}>Features</Link>
                <Link href={'#'}>Works </Link>
                <Link href={'#'}>Career </Link>
              </div>
              <div className="flex flex-col gap-3">
                <span className="font-bold mb-1"> <Link href={'#'}>Help</Link></span>
                <Link href={'#'}>Customer Support</Link>
                <Link href={'#'}>Delivery Details</Link>
                <Link href={'#'}>Terms & Conditions</Link>
                <Link href={'#'}>Privacy Policy</Link>
              </div>
              <div className="flex flex-col gap-3">
                <span className="font-bold mb-1"> <Link href={'#'}>FAQ</Link></span>
                <Link href={'#'}>Account</Link>
                <Link href={'#'}>Manage Deliveries</Link>
                <Link href={'#'}>Orders</Link>
                <Link href={'#'}>Payments</Link>
              </div>
              <div className="flex flex-col gap-3">
                <span className="font-bold mb-1"><Link href={'#'}>Resources</Link></span>
                <Link href={'#'}>Free eBooks</Link>
                <Link href={'#'}>Development Tutorial</Link>
                <Link href={'#'}>How to - Blog</Link>
                <Link href={'#'}>Youtube Playlist</Link>
              </div>
            </div>
            <div className="border-t-[2px] container pt-8 flex gap-4 items-center justify-between">
              <div>
                <p>Shop.co © 2000-2023, All Rights Reserved</p>
              </div>
              <div className="flex items-center gap-4">
                <img src="/visa.svg" alt="" />
                <img src="/visa_2.svg" alt="" />
                <img src="/paypal.svg" alt="" />
                <img src="/PayG.svg" alt="" />
              </div>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
